=== MyNextID/credentials/credential-definitions/boarding-pass/v1/input-fields/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Schema Template",
    "type": "object",
    "properties": {
        "fullName": {
            "title":"Full name",
            "description": "The full name of the recipient of this credential",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
              
        },
        "flightNumber":{
            "title": "Flight number",
            "description": "The official flight number for recipient",
            "type": "string"
        },
        "date":{
            "title": "Date",
            "description": "Date of the flight, formatted in ISO 8601 (YYYY-MM-DDThh:mm:ssZ)",
            "type": "string",
            "format": "date-time"
        },
        "boardingTime":{
            "title": "Boarding time",
            "description": "The scheduled time when recipient can begin boarding the flight",
            "type": "string"
        },
        "locationFrom":{
            "title": "Location from",
            "description": "The departure airport, station, or starting location of the journey",
            "type": "string"
        },
        "locationTo":{
            "title": "Location to",
            "description": "The destination airport, station, or final arrival location",
            "type": "string"
        },
        "gateNumber":{
            "title": "Gate number",
            "description": "The assigned gate where recipient should board their flight or transport",
            "type": "string"
        },
        "seatNumber":{
            "title": "Seat number",
            "description": "The designated seat assigned to the recipient for the journey",
            "type": "string"
        }
    },
    "required": ["fullName"]
}

=== MyNextID/credentials/credential-definitions/boarding-pass/v2/input-fields/example.json
{
    "fullName":  {
        "en": "John Doe"
    },
    "flightNumber": "KL1986",
    "date": "2026-01-02T15:04:05Z",
    "boardingTime": "2026-01-02T15:04:05Z",
    "locationFrom": "Ljubljana Jože Pučnik Airport (LJU)",
    "locationTo": "Amsterdam Airport Schiphol (AMS)",
    "gateNumber" : "A12",
    "seatNumber":  "14C"
}
