=== MyNextID/credentials/credential-definitions/certificate-of-attendance/v1/input-fields/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Certificate of Attendance Schema",
    "type": "object",
    "properties": {
        "fullName" : {
            "title": "Full name",
            "description": "The full name of the recipient of this credential",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }, "achievementTitle":{
            "title": "Achievement title",
            "description": "The title of the achievement awarded to the recipient",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        },"achievementDescription":{
            "title": "Achievement description",
            "description": "A detailed description of the achievement, including its significance or requirements",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }, "country":{
            "x-vocabulary": "country",
            "title": "Country",
            "description": "The full country name in text format (e.g., not an ISO code)",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }, "address":{
            "title": "Address",
            "description": "The recipient's full address, including street details and city",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }, "location":{
            "title": "Location",
            "description": "",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }, "url":{
            "title": "Website",
            "description": "The URL of the web resource.",
            "type": "string",
            "format": "uri"
        }, "startDate":{
            "title": "Start Date",
            "description": "The date and time when the credential or achievement begins, formatted in ISO 8601 (YYYY-MM-DDThh:mm:ssZ)",
            "type": "string",
            "format": "date-time"
        }, "endDate":{
            "title": "End Date",
            "description": "The date and time when the credential or achievement ends, formatted in ISO 8601 (YYYY-MM-DDThh:mm:ssZ)",
            "type": "string",
            "format": "date-time"
        }, "workload": {
            "title": "Duration in hours",
            "description": "The workload required to complete the credential or achievement, expressed as an ISO 8601 duration string (e.g., 'PT60H' for 60 hours)",
            "type": "string",
            "format": "duration"
        }, "awardingStatement":{
            "title": "Awarding statement",
            "description": "The statement displayed on the credential indicating that it has been awarded to the recipient",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                    "type": "string",
                    "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }
    },
    "required": [
        "achievementTitle",
        "country",
        "address",
        "url"
    ]
}

=== MyNextID/credentials/credential-definitions/certificate-of-attendance/v1/input-fields/example.json
{
     "fullName" : {
        "en": "John Doe"
    }, "achievementTitle":{
        "en": "Title of your Conference"
    },"achievementDescription":{
        "en": "Here you should describe the activity of the event for which the recipient is receiving the Certificate of Attendance."
    }, "country":{
        "en": "Slovenia"
    }, "address":{
        "en": "A Great Address 2, 2025 Spicetown"
    }, "location":{
        "en": "Conference center"
    }, "url": "https://www.example.com",
    "startDate": "2026-01-01T00:00:00Z",
    "endDate":"2026-02-01T00:00:00Z", 
    "workload":"PT60H",
    "awardingStatement":{
        "en": "is awarded to"
    }
}
