=== MyNextID/credentials/credential-definitions/confirmation-of-enrolment/v1/input-fields/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Confirmation of Enrolment",
    "type": "object",
    "properties": {
        "fullName":{
            "title": "Full name",
            "description": "The full name of the recipient of this credential",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        },"dateOfBirth":{
            "title":  "Date of birth",
            "description": "Date of birth of the recipient of this credential",
            "type": "string",
            "format": "date-time"

        },"placeOfBirth":{
            "title": "Country of birth",
            "description": "The country where the recipient was born",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        },"fullAddress":{
            "title": "City of birth",
            "description": "The recipient's full address, including street details and city",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        },"studentNumber":{
            "title": "Student number",
            "description": "The official student number used to uniquely identify the recipient",
            "type": "string"
        },"academicYear":{
            "title":  "Academic Year",
            "description": "The academic year associated with the credential or enrollment",
            "type": "string"
        }, "programmeTitle":{
            "title": "Programme Title",
            "description": "The official title of the academic programme or course of study",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }  
    }, "required": [
        "programmeTitle",
        "placeOfBirth",
        "fullAddress"
    ]
}

=== MyNextID/credentials/confirmation-of-enrolment/v1/input-fields/example.json
{
    "fullName":{
        "en": "John Doe"
    },"dateOfBirth":"1990-01-01T00:00:00Z",
    "placeOfBirth":{
        "en": "Slovenia"
    },"fullAddress":{
        "en": "A Great Address 2, 2025 Spicetown"
    },"studentNumber": "12-345-678",
    "academicYear": "2026",
    "programmeTitle":{
        "en": "Mechanical Engineering"
    }
}
