=== MyNextID/credentials/credential-definitions/visa/v1/input-fields/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Schema Template",
    "type": "object",
    "properties": {
        "fullName": {
            "title":"Full name",
            "description": "The full name of the recipient of this credential",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code. "
                }
            },
            "additionalProperties": false
              
        },
        "durationOfStay":{
            "title":"Duration of stay",
            "description": "Hours of stay.",
            "type": "string",
            "format": "duration"
        },
        "issuanceDate":{
            "title": "Issuance date",
            "description": "The date and time when the credential was issued, formatted in ISO 8601 (YYYY-MM-DDThh:mm:ssZ)",
            "type": "string",
            "format": "date-time"
        },
        "validUntil":{
            "title": "Valid until",
            "description": "The date and time until the credential is valid, formatted in ISO 8601 (YYYY-MM-DDThh:mm:ssZ)",
            "type": "string",
            "format": "date-time"
        },
        "visaNumber":{
            "title": "Visa number",
            "description": "The official visa number",
            "type": "string"
        },
        "passportNumber":{
            "title": "Passport number",
            "description": "The number of recipient passport",
            "type": "string"
        },
        "placeOfIssue":{
            "title":"Place of issue",
            "description": "The place of issuance of this credential",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        },
        "nationality":{
            "title":"Nationality",
            "description": "Nationality of the recipient of this credential",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        },
        "dateOfBirth":{
            "title": "Date of birth",
            "description": "The date and time of recipient birth, formatted in ISO 8601 (YYYY-MM-DDThh:mm:ssZ)",
            "type": "string",
            "format": "date-time"
        },
        "typeOfVisa":{
            "title":"Type of visa",
            "description": "Type of visa",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        },
        "entryType":{
            "title":"Entry type",
            "description": "Type of entry of recipient",
            "type": "object",
            "x-format": "languageMap",
            "patternProperties": {
                "^[a-z]{2}$": {
                "type": "string",
                "description": "A string value for a specific language code."
                }
            },
            "additionalProperties": false
        }

    },
    "required": ["fullName"]
}

=== MyNextID/credentials/credential-definitions/visa/v1/input-fields/example.json
{
    "fullName": {
        "en": "John Doe"
    },
    "durationOfStay": "PT60H",
    "issuanceDate":"2026-01-02T15:04:05Z",
    "validUntil": "2030-01-02T15:04:05Z",
    "visaNumber": "123456",
    "passportNumber": "654321",
    "placeOfIssue": {
        "en": "Slovenia"
    },
    "nationality": {
        "en": "Slovenian"
    },
    "dateOfBirth" : "1990-01-01T00:00:00Z",
    "typeOfVisa": {
        "en":"Tourist Visa"
    },
    "entryType": {
        "en":"Single Entry"
    }
}
